### ISSUE TITLE
Loopback oracle connector issues

### ISSUE THREAD

**Issue by jeyaraj87** [strongloop/loopback-connector-oracle#163]
any connection from our loopback application to oracle db becomes stale after 1 hour if the application is in idle state. I have to manually restart the application to get the connection back. Can you provide some insights on this issue.

**Comment by cjbj** [comment]
Commonly firewalls and DB resource profiles are implicated in connections being closed prematurely.

General advice would be  to close the connection when it is not being used, so that resources are freed up for other users.   Specific advice depends on business and architectural practices, which only you know.

**Comment by jeyaraj87** [comment]
@cjbj  : Thanks.  do you have any sample query written using loopback oracle connector which has connection open and close. We though connector is taking care of the connection. I am pasting my sample query which we are using in our application. we don't open and close connection before query call. 

This query has been written in model Js file. 
modelName.find(searchParams, function (err, result) {
});

**Comment by cjbj** [comment]
@jeyaraj87 my domain of expertise ends at the [node-oracledb](https://github.com/oracle/node-oracledb) API.

**Comment by raymondfeng** [comment]
@cjbj Does the node-oracledb connection pool handle stale connections?

**Comment by cjbj** [comment]
@raymondfeng node-oracledb's connection pool does its best with stale connections.  There are some tweaks coming soon in node-oracledb 3: https://github.com/oracle/node-oracledb/issues/960#issuecomment-412793112

Re-creating connections has a cost, so it would be better to fix the root cause of the network termination. Of course, connections can die at anytime so apps still need to have appropriate error handling if `execute()` fails due to a connection issue. 

PS @raymondfeng production doc is at https://oracle.github.io/node-oracledb/doc/api.html

**Comment by jeyaraj87** [comment]
@raymondfeng : poolPingInterval is not supported by loopback-connector-oracle": "4.1.0".

poolTimeout is not solving our case either. I have tried few combination of values such as 0, 60,180

**Comment by tinker20** [comment]
@raymondfeng I am facing the same issue. Here is my dataSources.json

```
  "oracle": {
    "host": "xx.xxx.xx.xxx",
    "port": 1521,
    "database": "xe",
    "password": "xxxxxxxxx",
    "name": "oracle",
    "tns": "",
    "user": "xxxxxxx",
    "connector": "oracle",
    "minConn":10,
    "maxConn":200,
    "incrConn":10,
    "timeout": 0
  }
```
@jeyaraj87 Were you able to fix this issue?

**Comment by cjbj** [comment]
@tinker20 what is the exact issue?  Are you seeing an error?  What is the underlying node-oracledb version are you using?  What Oracle Client version is it linking with (run [version.js](https://github.com/oracle/node-oracledb/blob/master/examples/version.js))?

Also, you should review your maxConn size, since each connection in use will require a thread, and Node.js limits the number of threads to 128.  See https://oracle.github.io/node-oracledb/doc/api.html#numberofthreads  (Loopback's `maxConn` is node-oracledb's `poolMax`).

**Comment by tinker20** [comment]
@cjbj The underlying `node-oracledb` version that the connector is using is `"oracledb": "2.2.0"`. What is the ideal datasource configuration that I need to use?

I am using this 
```
  "oracle": {
    "host": "xx.xxx.xx.xxx",
    "port": 1521,
    "database": "xe",
    "password": "xxxxxxxxx",
    "name": "oracle",
    "tns": "",
    "user": "xxxxxxx",
    "connector": "oracle",
    "minConn":0,
    "maxConn":128,
    "incrConn":2,
    "timeout": 0
  }
```

**Comment by tinker20** [comment]
@cjbj The oracle client library version that I'm using is 12.2.0. I hope you are seeking for the Oracle instant client version, right?

**Comment by tinker20** [comment]
@cjbj @raymondfeng Any update on the above issue?
